import os
import datetime
import pytz
import requests
import time
from apscheduler.schedulers.background import BackgroundScheduler

# 1. កំណត់តម្លៃ Telegram API ពី Environment Variables (សុវត្ថិភាពជាង)
TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

def send_gold_report():
    # កំណត់ម៉ោងជាតំបន់អាស៊ី/ភ្នំពេញ (GMT+7)
    cambodia_tz = pytz.timezone('Asia/Phnom_Penh')
    now = datetime.datetime.now(cambodia_tz)
    date_str = now.strftime("%A ទី %d %B %Y")

    # អត្ថបទរបាយការណ៍គំរូតាម Style របស់បង (បងអាចចូលមកកែប្រែចំណុចបច្ចេកទេសត្រង់នេះជារៀងរាល់ថ្ងៃ)
    message = f"""📊 *របាយការណ៍វិភាគមាសប្រចាំថ្ងៃ (XAU/USD)*
*Institutional Grade Analysis (OANDA Data) | {date_str}*

---

### 🌍 ១. ស្ថានភាព Macro & ព័ត៌មាន (Fundamental)

*📊 និន្នាការ៖ Bearish Momentum 📉*
• *Market Overview:* ទីផ្សារមាសកំពុងស្ថិតក្រោមសម្ពាធលក់យ៉ាងខ្លាំង ដោយសារ DXY រក្សាភាពរឹងមាំ និងគោលជំហរ "Higher-for-longer" របស់ Fed។

---

### 🎯 ២. INTRADAY EXECUTION ROADMAP

• *Daily Bias (D1):* Bearish 📉 (តម្លៃរត់ក្រោមខ្សែបណ្តុំ Moving Averages សំខាន់ៗ)។
• *Intraday Supply Zone:* *$4,480 – $4,500* (តំបន់រង់ចាំ SELL)
• *HTF Key Support:* *$4,376* (ខ្សែការពារចុងក្រោយ)

---

### ⚠️ ៣. ការគ្រប់គ្រងហានិភ័យ (Risk Management)

• *Strategy:* យុទ្ធសាស្ត្រចម្បងគឺ *"Sell on Rallies"* (រកកន្លែង SELL ពេលតម្លៃ Pullback ឡើងលើ)។
• *Risk per Trade:* រក្សាការ Risk ត្រឹម *1%* ប៉ុណ្ណោះ។

---
*Generated by E11 Lab Bot 🚀 | 📌 ព័ត៌មាននេះសម្រាប់ Educational Purpose ប៉ុណ្ណោះ*"""

    # ផ្ញើទៅកាន់ Telegram API
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }
    
    try:
        response = requests.post(url, json=payload)
        if response.status_code == 200:
            print("Report sent successfully!")
        else:
            print(f"Failed to send message: {response.text}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    # កំណត់ការផ្ញើស្វ័យប្រវត្តិតាមម៉ោង (Cron Job)
    scheduler = BackgroundScheduler(timezone="Asia/Phnom_Penh")
    
    # ឧទាហរណ៍៖ ផ្ញើរាល់ព្រឹក ម៉ោង 8:00 AM (ម៉ោងនៅកម្ពុជា)
    scheduler.add_job(send_gold_report, 'cron', hour=8, minute=0)
    scheduler.start()
    
    print("Gold Analysis Bot is running...")
    
    # រក្សាឱ្យ Script រត់រហូត
    try:
        while True:
            time.sleep(1)
    except (KeyboardInterrupt, SystemExit):
        scheduler.shutdown()
      
